### PR TITLE
Add custom repository variables

### PR DESCRIPTION
**Pull request by Quafadas**
For the situation, in which one is attempting to use this action in a (corporate) environment, where standard repositories are not available, but proxied by some other tool - e.g. antifactory.

### CODE REVIEW

**Review by tgodzik — CHANGES_REQUESTED** [review]
Thanks for the contribution! Looks like you need to run prettifier first :(

**Comment by Quafadas** [comment]
Arg - I think I always forget that :-/, thanks for the tip.

**Review by tgodzik — APPROVED** [review]
Thanks!

**Comment by ghostbuster91** [comment]
Hi @tgodzik could you please release a new version? The latest release was in February. I know that I can use the action with the latest changes either by pinning it to a particular commit or the main branch but we prefer to use standard tags. Many thanks!

**Comment by tgodzik** [comment]
I tagged a new version, I think that should be enough? Or do we need to release it on the marketplace? If the last one is needed then we would need to ask Alex to enable that for the org.

**Comment by ghostbuster91** [comment]
> I tagged a new version, I think that should be enough? Or do we need to release it on the marketplace?

I checked and I am able to use it by specifying the exact tag `@v1.3.6` but using simply `@v1` doesn't work.

**Comment by tgodzik** [comment]
Ach, it's because everything is based on tags. I updated the tags to the newest version

**Pull request merged**
