### PR TITLE
Add support for `--jvm-index`

### PR DESCRIPTION
**Pull request by mkurz**
I set up a custom coursier index file that containts Java 21 (and soon newer) early access builds:

* https://github.com/mkurz/jvm-index/blob/adoptium_temurin_eaps/index.json
* `cs java --available --jvm-index https://github.com/mkurz/jvm-index/raw/adoptium_temurin_eaps/index.json`

(If you are interested it was done with this [hacked commit](https://github.com/mkurz/jvm-index/commit/6441337a921fcbd7f3fd9d11401400fd19e2080d) so you can generate the json file yourself locally if you want).

Reason is I want to run tests for the Play Framework with upcoming [Java 21 LTS first release candidate (which is ea build 35)](https://mail.openjdk.org/pipermail/jdk-dev/2023-August/008059.html) with our GitHub actions workflows. To set my index it needs support in your action.

Thanks!

### CODE REVIEW

**Comment by mkurz** [comment]
I updated the dist using the same node version and commands like in your workflows (I do have `nvm` installed):
https://github.com/coursier/setup-action/blob/6a582d7f7292a865e72c497ca64c3ef447cdb6c7/.github/workflows/update-dist.yml#L13-L18

**Comment by mkurz** [comment]
It works!
See https://github.com/playframework/playframework/actions/runs/5912047986/job/16035189435?pr=11925#step:7:46

```
Install JVM
  /opt/hostedtoolcache/cs/2.1.2/x64/cs java --jvm adoptium:21-ea34 --jvm-index https://github.com/mkurz/jvm-index/raw/adoptium_temurin_eaps/index.json -version
  Still downloading:
  https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21%2B34-ea-beta/OpenJDK21U-jdk_x64_linux_hotspot_ea_21-0-34.tar.gz (68.12 %, 141565184 / 207803420)
  
  openjdk version "21-beta" 2023-09-19
  OpenJDK Runtime Environment Temurin-21+34-202308031254 (build 21-beta+34-ea)
  OpenJDK 64-Bit Server VM Temurin-21+34-202308031254 (build 21-beta+34-ea, mixed mode, sharing)
  /opt/hostedtoolcache/cs/2.1.2/x64/cs java-home --jvm adoptium:21-ea34 --jvm-index https://github.com/mkurz/jvm-index/raw/adoptium_temurin_eaps/index.json
  /home/runner/.cache/coursier/arc/https/github.com/adoptium/temurin21-binaries/releases/download/jdk-21%2[52](https://github.com/playframework/playframework/actions/runs/5912047986/job/16035189435?pr=11925#step:7:54)B34-ea-beta/OpenJDK21U-jdk_x64_linux_hotspot_ea_21-0-34.tar.gz/jdk-21+34
```

Would it be possible to get this merged and released with 1.3.5? Would be great, thanks!

**Comment by mkurz** [comment]
Anyone?

**Comment by tgodzik** [comment]
Looks good to me, though would love the opinion of @alexarchambault just to be sure. If Alex doesn't have time I will try to look further and maybe merge next week.

**Comment by mkurz** [comment]
@tgodzik Great, thanks!

**Review by alexarchambault — APPROVED** [review]
Looks good to me, thanks @mkurz!

I reverted the commit updating the dist files, as this is not needed (these are updated before tests on the CI, and pushed as a commit when on the `main` branch)

**Comment by mkurz** [comment]
@alexarchambault @tgodzik Can you please move the `v1.3` and `v1` tag to the latest `v1.3.4` release? Thanks!

**Comment by alexarchambault** [comment]
@mkurz That slipped my attention, should be fine now

**Comment by mkurz** [comment]
Thanks!

**Pull request merged**
