### PR TITLE
Upgrade to Node 16

### LINKED ISSUE #281: Upgrade to node 16
Actions using **Node 12** are considered deprecated and encouraged to upgrade to **Node 16**.
For reference: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

I wonder if all that is needed is just changing [this line](https://github.com/coursier/setup-action/blob/main/action.yml#L24).

```diff
runs:
-  using: 'node12'
+  using: 'node16'
  main: 'dist/index.js'
```

And refreshing the `package-lock` using **Node 16**.

If so, I am more than happy to help.
But, if something else is required I would need assistance / guidance.

### PR DESCRIPTION
**Pull request by BalmungSan**
Fixes #281

-----

> If this is the right way to do this then I would do the same on https://github.com/coursier/cache-action

### CODE REVIEW

**Comment by BalmungSan** [comment]
@alexarchambault I guess this is done?
BTW, not sure if this change should imply an increase in the version.

**Comment by alexarchambault** [comment]
> BTW, not sure if this change should imply an increase in the version.

You mean, a major or minor version bump? I don't know, I guess I'll tag the next version as `v1.3.0`.

**Comment by alexarchambault** [comment]
Thanks for this PR, it's merged!

**Comment by BalmungSan** [comment]
> You mean, a major or minor version bump? I don't know, I guess I'll tag the next version as v1.3.0.

@alexarchambault I mean, I don't know either. That is why I just leave the question since not sure what is the recommendation or standard followed by other actions.

**Pull request merged**
